[pytest]
addopts = --base-url https://www.globalsqa.com/angularJs-protractor/BankingProject/
markers =
    smoke: Quick, critical tests to ensure core functionality is working.
    regression: Comprehensive tests to verify that recent code changes havent broken existing features
    customer: Tests exclusively related to the Customer flows.
    manager: Tests exclusively related to the Bank Manager flows (adding customers, opening accounts).